Algoritmo "consumo de combustivel"
// Disciplina   : PA
// Professor   : Edilma Bindá
// Autor(a)    : Pedro Henrique Assunção Medeiros
// Data atual  : 09/03/2023
Var
media, km, combustivel:real

Inicio

escreval ("Determine a distância percorrida: ")
leia (km)

escreval ("Determine o total de combustivel gasto: ")
leia (combustivel)

//processamento

media <- km/combustivel

//saida

escreval ("o consumo médio do automóvel é: ", media)


Fimalgoritmo