Algoritmo "Converão de Celsius em Fahrenheit"
// Disciplina   : PA
// Professor   : Edilma Bindá
// Autor(a)    : Pedro Henrique Assunção Medeiros
// Data atual  : 09/03/2023
Var
temperatura, graus:real


Inicio
escreval ("Insira quantos graus celsius deseja converter: ")
leia (graus)

//processamento
temperatura <-(9*graus+160)/5

//final
escreval ("A temperatura em fahrenheit é: ", temperatura)


Fimalgoritmo