Algoritmo "media bimestral"
// Disciplina   : PA
// Professor   : Edilma Bindá
// Autor(a)    : Pedro Henrique Assunção Medeiros
// Data atual  : 09/03/2023
Var
media, total:real
nome:caractere

Inicio

escreval ("Digite seu nome: ")
leia (nome)

escreval ("Insira suas três ultimas notas somadas: ")
leia (total)

//processamento

media <- total/3

//saida

escreval ("A sua média do bimestre, ", nome ,", é: ", media)


Fimalgoritmo